apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: emoloic/converter:latest
        resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "1Gi"
              cpu: 1
        envFrom:
          - configMapRef:
              name: converter-configmap
          - secretRef:
              name: converter-secret