apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8sCluster
  version: "1.21"
  region: ap-south-1

managedNodeGroups:
  - name: k8sNodes
    instanceType: t3.medium
    minSize: 2
    maxSize: 2